# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cyrus.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63yrus.proto\x12\x05\x63yrus\"\x1d\n\x05Vec2D\x12\t\n\x01X\x18\x01 \x01(\x02\x12\t\n\x01Y\x18\x02 \x01(\x02\"\x16\n\x05\x41ng2D\x12\r\n\x05\x41ngle\x18\x01 \x01(\x02\"R\n\x05State\x12\x1e\n\x08Position\x18\x01 \x01(\x0b\x32\x0c.cyrus.Vec2D\x12\x1a\n\x04\x42ody\x18\x02 \x01(\x0b\x32\x0c.cyrus.Ang2D\x12\r\n\x05\x43ycle\x18\x03 \x01(\x05\"6\n\nActionDash\x12\r\n\x05Power\x18\x01 \x01(\x02\x12\x19\n\x03\x44ir\x18\x02 \x01(\x0b\x32\x0c.cyrus.Ang2D\"\'\n\nActionTurn\x12\x19\n\x03\x44ir\x18\x01 \x01(\x0b\x32\x0c.cyrus.Ang2D\"X\n\x06\x41\x63tion\x12!\n\x04\x44\x61sh\x18\x01 \x01(\x0b\x32\x11.cyrus.ActionDashH\x00\x12!\n\x04Turn\x18\x02 \x01(\x0b\x32\x11.cyrus.ActionTurnH\x00\x42\x08\n\x06\x61\x63tion\"B\n\x06Reward\x12\r\n\x05Value\x18\x01 \x01(\x02\x12\r\n\x05\x43ycle\x18\x02 \x01(\x05\x12\x0c\n\x04Unum\x18\x03 \x01(\x05\x12\x0c\n\x04\x44one\x18\x04 \x01(\x08\"\x1d\n\x0cStartEpisode\x12\r\n\x05\x43ycle\x18\x01 \x01(\x05\"i\n\x0eTrainerRequest\x12+\n\x0cStartEpisode\x18\x01 \x01(\x0b\x32\x13.cyrus.StartEpisodeH\x00\x12\x1f\n\x06Reward\x18\x02 \x01(\x0b\x32\r.cyrus.RewardH\x00\x42\t\n\x07request\"\x10\n\x02OK\x12\n\n\x02OK\x18\x01 \x01(\x08\x32h\n\rSampleService\x12.\n\rGetBestAction\x12\x0c.cyrus.State\x1a\r.cyrus.Action\"\x00\x12\'\n\tSetReward\x12\r.cyrus.Reward\x1a\t.cyrus.OK\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cyrus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VEC2D']._serialized_start=22
  _globals['_VEC2D']._serialized_end=51
  _globals['_ANG2D']._serialized_start=53
  _globals['_ANG2D']._serialized_end=75
  _globals['_STATE']._serialized_start=77
  _globals['_STATE']._serialized_end=159
  _globals['_ACTIONDASH']._serialized_start=161
  _globals['_ACTIONDASH']._serialized_end=215
  _globals['_ACTIONTURN']._serialized_start=217
  _globals['_ACTIONTURN']._serialized_end=256
  _globals['_ACTION']._serialized_start=258
  _globals['_ACTION']._serialized_end=346
  _globals['_REWARD']._serialized_start=348
  _globals['_REWARD']._serialized_end=414
  _globals['_STARTEPISODE']._serialized_start=416
  _globals['_STARTEPISODE']._serialized_end=445
  _globals['_TRAINERREQUEST']._serialized_start=447
  _globals['_TRAINERREQUEST']._serialized_end=552
  _globals['_OK']._serialized_start=554
  _globals['_OK']._serialized_end=570
  _globals['_SAMPLESERVICE']._serialized_start=572
  _globals['_SAMPLESERVICE']._serialized_end=676
# @@protoc_insertion_point(module_scope)
