name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - cyrus2d

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libboost-all-dev cmake

      - name: Install librcsc
        run: |
          git clone https://github.com/helios-base/librcsc.git
          cd librcsc
          git checkout 19175f339dcb5c3f61b56a8c1bff5345109f22ef
          mkdir build
          cd build
          cmake ..
          make
          sudo make install

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make
          cd bin
          mkdir lib
          cp ~/local/lib/libr* lib/

      - name: Create zip file
        run: |
          cd build
          mv bin cyrus
          cd cyrus
          zip -r ../../cyrus.zip *

      # ------------------------------------------- Release
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/cyrus.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "8"
          release_name: "8"
          release_body: "FOXSY CYRUS BASE"
          draft: false
          prerelease: false
