name: Build and Release

on:
  push:
    branches:
      - cyrus2d

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create zip file
        run: |
          zip -r cyrus.zip src

      # - name: Create GitHub Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.sha }}
      #     release_name: Release ${{ github.sha }}
      #     draft: false
      #     prerelease: false
      # ------------------------------------------- Release
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.workspace }}/cyrus.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "1"
          release_name: "2"
          release_body: "FOXSY CYRUS BASE"
          draft: false
          prerelease: false
      # - name: Upload Release Asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: build/cyrus.zip
      #     asset_name: cyrus.zip
      #     asset_content_type: application/zip
